### ISSUE TITLE
Caipirinha service fails on start

### ISSUE THREAD

**Issue by pardini01** [eubr-bigsea/caipirinha#24]
After fixing the caipirinha Dockerfile as described on #23 and after building the Docker images of all services, the caipirinha service fails to start when running `docker-compose up` on the docker-lemonade folder:

```
caipirinha_1    | Traceback (most recent call last):
caipirinha_1    |   File "/usr/local/caipirinha/caipirinha/manage.py", line 1, in <module>
caipirinha_1    |     from flask_migrate import Migrate, MigrateCommand
caipirinha_1    | ImportError: cannot import name 'MigrateCommand' from 'flask_migrate' (/usr/local/lib/python3.7/site-packages/flask_migrate/__init__.py)
caipirinha_1    | Error on DB migration
docker-lemonade_caipirinha_1 exited with code 1
```

My setup is: macOS BigSur, Docker version 20.10.6, docker-compose version 1.29.1.

**Comment by waltersf** [comment]
Latest version in master branch fixed it. Could you please test it again?

**Comment by pardini01** [comment]
It is working now. Thanks!

**Comment by waltersf** [comment]
Fixed
